In [1]:
import numpy as np
print("Библиотека NumPy импортирована.")

Библиотека NumPy импортирована.


In [2]:
## Создание массивов 
list_data = [1, 2, 3, 4, 5, 6]
array_from_list = np.array(list_data)

print("Массив из списка:")
print(array_from_list)

Массив из списка:
[1 2 3 4 5 6]


In [10]:
## Использование функций zeros, ones, arange
zeros_array = np.zeros((3, 4)) 
print("\nМассив из нулей (3x4):")
print(zeros_array)

ones_array = np.ones((2, 3)) 

print("\nМассив из единиц (2x3):")
print(ones_array)

range_array = np.arange(0, 10, 2) 

print("\nМассив диапазона (arange):")
print(range_array)


Массив из нулей (3x4):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Массив из единиц (2x3):
[[1. 1. 1.]
 [1. 1. 1.]]

Массив диапазона (arange):
[0 2 4 6 8]


In [9]:
## Вывод формы и тип данных
print(f"Массив: {array_from_list}")
print(f"Форма массива (shape): {array_from_list.shape}")
print(f"Тип данных элементов (dtype): {array_from_list.dtype}")

print(f"\nФорма массива zeros_array (shape): {zeros_array.shape}")
print(f"Тип данных элементов zeros_array (dtype): {zeros_array.dtype}")

Массив: [1 2 3 4 5 6]
Форма массива (shape): (6,)
Тип данных элементов (dtype): int64

Форма массива zeros_array (shape): (3, 4)
Тип данных элементов zeros_array (dtype): float64


In [8]:
## Индексирование и срезы
print(f"Исходный массив: {array_from_list}")

element_at_index_2 = array_from_list[2] 
print(f"Элемент по индексу 2: {element_at_index_2}")

subarray_slice = array_from_list[1:4] 
print(f"Срез массива (индексы с 1 по 3): {subarray_slice}")

Исходный массив: [1 2 3 4 5 6]
Элемент по индексу 2: 3
Срез массива (индексы с 1 по 3): [2 3 4]


In [6]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(f"Массив A: {a}")
print(f"Массив B: {b}")

# Поэлементное сложение
addition_result = a + b
print(f"Результат сложения A + B: {addition_result}")

# Поэлементное умножение
multiplication_result = a * b
print(f"Результат умножения A * B: {multiplication_result}")

Массив A: [10 20 30 40]
Массив B: [1 2 3 4]
Результат сложения A + B: [11 22 33 44]
Результат умножения A * B: [ 10  40  90 160]


In [7]:
data = np.array([10, 15, 20, 25, 30])

print(f"Данные для статистики: {data}")

# Вычисление среднего значения (mean)
mean_value = np.mean(data)
print(f"Среднее значение (mean): {mean_value}")

# Вычисление суммы (sum)
sum_value = np.sum(data)
print(f"Сумма всех элементов (sum): {sum_value}")

Данные для статистики: [10 15 20 25 30]
Среднее значение (mean): 20.0
Сумма всех элементов (sum): 100
